### ISSUE TITLE
Reading web netCDF data: Connection timed out when looking for https resource (but it timed out looking for http resource)

### ISSUE THREAD

**Issue by lesserwhirls** [Unidata/netcdf-java#140]
From the [mailing list](https://www.unidata.ucar.edu/mailing_lists/archives/netcdf-java/2019/msg00022.html)

---

When using `cdm-core-5.2.0`, when attempting to access a netCDF resource on a server that serves https on port 443 but does not serve http on port 80, attempting to access the https resource fails but with a message indicating it tried port 80.

See redacted stack trace below.

I wonder if it is related to the diff at https://github.com/Unidata/netcdf-java/compare/v5.1.0...v5.2.0#diff-89b73930910f1f42a6af87d6d282a372 but this is speculation.

~~~
Failed to open netCDF file https://fqdn-of-server/path/to/netcdf_resource.nc
...
Caused by: ucar.httpservices.HTTPException: org.apache.http.conn.HttpHostConnectException: Connect to fqdn-of-server:80 [fqdn-of-server/x.x.x.x] failed: Connection timed out: connect
        at ucar.httpservices.HTTPMethod.executeRaw(HTTPMethod.java:373)
        at ucar.httpservices.HTTPMethod.execute(HTTPMethod.java:314)
        at ucar.unidata.io.http.HTTPRandomAccessFile.doConnect(HTTPRandomAccessFile.java:136)
        at ucar.unidata.io.http.HTTPRandomAccessFile.<init>(HTTPRandomAccessFile.java:60)
        at ucar.unidata.io.http.HTTPRandomAccessFile.<init>(HTTPRandomAccessFile.java:40)
        at ucar.nc2.NetcdfFile.getRaf(NetcdfFile.java:448)
        at ucar.nc2.NetcdfFile.open(NetcdfFile.java:338)
        at ucar.nc2.NetcdfFile.open(NetcdfFile.java:305)
        at ucar.nc2.NetcdfFile.open(NetcdfFile.java:290)
        at ucar.nc2.NetcdfFile.open(NetcdfFile.java:278)
        at wres.io.reading.nwm.NWMTimeSeries.openFile(NWMTimeSeries.java:194)
        ... 52 more
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to fqdn-of-server:80 [fqdn-of-server/x.x.x.x] failed: Connection timed out: connect
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:156)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
        at ucar.httpservices.HTTPMethod.executeRaw(HTTPMethod.java:366)
        ... 62 more
Caused by: java.net.ConnectException: Connection timed out: connect
        at java.base/java.net.PlainSocketImpl.waitForConnect(Native Method)
        at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:107)
        at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
        at java.base/java.net.Socket.connect(Socket.java:591)
        at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
        ... 72 more
~~~

**Comment by lesserwhirls** [comment]
@DennisHeimbigner - any thoughts on this one?

**Comment by rschmunk** [comment]
Possibly a related issue: I am trying to figure out why when acquiring a remote dataset, my Panoply app using NJ 5.2 is displaying a userid/passwd credential dialog twice. In doing so I am checking the server logs to see what requests are being made. Note that this is a static file on a website, not something on a THREDDS or other data server. So I am specifically requesting myfile.nc with an HTTPS (port 443) link when calling `NetcdfDataset.acquireDataset`. What I see in the server logs follows:

- GET myfile.nc.dds on port 80 - redirects to port 443
- GET myfile.nc.dds on port 443 - response 401, because directory is passwd-protected
- GET myfile.nc.dds on port 80 - redirects to port 443
- GET myfile.nc.dds on port 443 - response 401
- GET myfile.nc.dds on port 443 - response 404, userid/passwd supplied but file does not exist
- GET myfile.nc.dmr.xml on port 80 - redirects to port 443
- GET myfile.nc.dmr.xml on port 443 - response 404, file does not exist
- HEAD myfile.nc?req=header on port 80 - redirects to port 443
- HEAD myfile.nc?req=header on port 443 - response 200, file exists
- HEAD myfile.nc on port 80 - redirects to port 301
- HEAD myfile.nc on port 443 - response 401, it wants the password again?
- HEAD myfile.nc on port 443 - response 200, userid/passwd supplied and file exists
- GET myfile.nc on port 80 - redirects to port 301
- GET myfile.nc on port 443 - response 200, complete file (it's just 66 kb) sent back
- HEAD myfile.nc on port 80 - redirects to port 301
- HEAD myfile.nc on port 443 - response 401, it wants the password again?
- HEAD myfile.nc on port 443 - response 200, userid/passwd supplied and file exists
- GET myfile.nc on port 80 - redirects to port 301
- GET myfile.nc on port 443 - response 200, complete file (it's just 66 kb) sent back

Going back and using a version of Panoply based on NJ 5.1, I find that the credential dialog only gets displayed once, and there are no calls to port 80 when trying to acquire the dataset. 

It's quite possible that the display of the credentials dialog twice is my fault in trying to figure out migrating from NJ 5.1 to 5.2. But all the calls to port 80 looks like a bug in 5.2.

**Comment by lesserwhirls** [comment]
Thank you for the report @rschmunk! I think these are related issues, likely introduced by PR Unidata/netcdf-java#117. Those changes are documented [here](https://github.com/DennisHeimbigner/netcdf-java/commit/30d708e957a34c72edd8988a5b75ab3b4395b61b#diff-05817f0c238dc4e9275aae895526ccd1). I meant to get this specific doc into our main docset, but it didn't make it (my apologies).

**Comment by DennisHeimbigner** [comment]
What is port 301 and why is it being redirected to?

**Comment by rschmunk** [comment]
@DennisHeimbigner, Sorry, all those "redirects to port 301" should be "redirects to port 443".

**Comment by DennisHeimbigner** [comment]
This is a bit complex (probably over complex). When you make a request to a server,
it is the context of a set of "credentials providers". This set is associated with
an HTTPSession instance. So if you make server requests with different HTTPSession
instances, then the user+password dialog will repeat once for each of those
instances. Determining this requires looking at the code  and cannot be determined
at the low level you provide.

**Comment by rschmunk** [comment]
@DennisHeimbigner, The only thing my code does directly vis a vis HTTPSession is to call its setGlobalUserAgent and setGlobalCredentialsProvider methods.

One thing I have discovered in the last few days is that the problem with the authentication dialog appearing twice, is that there are multiple getCredentials calls coming to my credentials provider, and that at some point, these calls switch from including a realm to instead specifying null. My provider previously paid no attention to the specified realm, but now does so and thinks it needs to create a second set of credentials.

**Comment by rschmunk** [comment]
Pinging to see if anyone has looked into this further. The problem with trying to acquire a remote dataset from a URL that specifically says https, but finding that NJ is making queries to port 80 during the process is new to NJ 5.2. This does not occur when using software based on NJ 5.1.

**Comment by rschmunk** [comment]
As an FYI, I will post a new Panoply release the next coupe days base on netCDF-Java 5.1. The load-remote issues prevent me from using NJ 5.2 or later.

**Comment by lesserwhirls** [comment]
Hello @rschmunk - I don't have an update to provide on my end. There was a pull request to address the issue (Unidata/netcdf-java#141), but the tests are failing, and I think I'm holding that up as I need to produce a video on how to get the debugger setup in IntelliJ for this situation. I'm going to try to work on that today, but unfortunately I don't think a fix will be in by the time you release the next version of Panoply. I will try to get Unidata/netcdf-java#149 addressed in 5.3, so at least both of these will be in the 5.3 release of netCDF-Java, but for now, it's best to stick with 5.2.

**Comment by bickelj** [comment]
See https://www.unidata.ucar.edu/mailing_lists/archives/netcdf-java/2019/msg00025.html

**Comment by rschmunk** [comment]
I spent some time this evening poking at the issues I described above using the latest NJ 5.3 snapshot, along with a bunch of additional logging msgs. I have a better idea of the process but didn't actually solve anything.

My code calls `HttpSession.setGlobalCredentialsProvider` and then `NetcdfDataset.acquireDataset`. The initial requests for the filename with appended "dds", "dmr.xml" and "?req=header" all occur because `DatasetUrl` is trying to figure out what sort of server and remote file it is trying to access. Early on it hits the requirement for a user ID and password, and my code flashes a dialog to get them, and caches the resulting `Credentials`. Thus, even though resulting calls to the server use different `HttpSession` instances, most successfully use the cached credentials.

To me the most critical issue is that after several successful requests to the server using the cached credentials, my authentication manager receives a request in which the `AuthScope` has changed — the realm has mysteriously changed from the "Please request a password from the webmaster" msg from the server to "<any realm>". So the user gets a second userid/passwd request even though the first was successful. Using NJ 5.1, the credential request with the changed realm doesn't happen.

I had no success figuring out why every request was first being made to port 80 even though the dataset URL explicitly says https. I wondered if this might be something silly related to an update in the version of Apache HttpClient used by netCDF-Java, but I see that was last updated in August, prior to the release of 5.1. And I see none of these requests to port 80 when using NJ 5.1.

**Comment by bickelj** [comment]
> I had no success figuring out why every request was first being made to port 80 even though the dataset URL explicitly says https. I wondered if this might be something silly related to an update in the version of Apache HttpClient used by netCDF-Java, but I see that was last updated in August, prior to the release of 5.1. And I see none of these requests to port 80 when using NJ 5.1.

To be more explicit than the suggestion in https://www.unidata.ucar.edu/mailing_lists/archives/netcdf-java/2019/msg00025.html:
1. Apply pull request 141 to 5.3.0-tagged code (if I recall correctly it was 5.3.0).
2. Change line 355 of HTTPMethod (here https://github.com/Unidata/netcdf-java/pull/141/files#diff-ba10eb3354e2a26749dc76f46daa4fd7) to use the last three-parameter constructor of HttpHost (here https://hc.apache.org/httpcomponents-core-ga/httpcore/apidocs/org/apache/http/HttpHost.html#HttpHost(java.lang.String,%20int,%20java.lang.String)) instead of the one-parameter constructor. I think the one-parameter constructor fills the scheme in as http (see https://hc.apache.org/httpcomponents-core-ga/httpcore/apidocs/org/apache/http/HttpHost.html#DEFAULT_SCHEME_NAME).

This resolves the https-requests-becoming-http-requests issue for me.

**Comment by rschmunk** [comment]
@bickelj, Thanks very much, for the more detailed instructions. Implementing these changes resulted in no second, unneeded request for the credentials. I'll doublecheck the issue with unnecessary requests to port 80 on Monday when I can monitor the office server log.
